"""
Django settings for proyectHotel project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xd(v!^5a#ot84t&-1kah%oe#66i3blq@)nqf7f&+e31w=y3d=^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'appHotel',
    'rest_framework',
    'rest_framework_simplejwt',
    "corsheaders",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'proyectHotel.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'proyectHotel.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'appHotel.Usuario'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "https://smpjwjtp-5173.brs.devtunnels.ms", # tunel para solo pruebas de demostracion
]
CORS_ALLOW_CREDENTIALS = True

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),  # Token válido por 1 día
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # Refresh válido por 7 días
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# settings.py (añadir al final)
PAYPAL_CONFIG = {
    'mode': 'sandbox',
    'client_id': 'AbFvBIAoq8hFuPL-o6_RNr-fVtyc4nSRpUhqR9cGXCYUeKTi19sJMki9FkHFx_TnVIkaMPxi4z_Kj3BR',
    'client_secret': 'EEEg1lSddMgSjVh5Id5uHiUG_AbU1fZOGNoFYVqP4KLYPbm_PsSf5nPJVboQ4TbA3RRaiR672h-WfuD1'
}

PAYPAL_SANDBOX_MODE = DEBUG
PAYPAL_CLIENT_ID = 'AbFvBIAoq8hFuPL-o6_RNr-fVtyc4nSRpUhqR9cGXCYUeKTi19sJMki9FkHFx_TnVIkaMPxi4z_Kj3BR'
PAYPAL_SECRET = 'EEEg1lSddMgSjVh5Id5uHiUG_AbU1fZOGNoFYVqP4KLYPbm_PsSf5nPJVboQ4TbA3RRaiR672h-WfuD1'
PAYPAL_ENVIRONMENT = 'sandbox'
PAYPAL_BASE_URL = 'https://api-m.sandbox.paypal.com'
if not DEBUG and PAYPAL_SANDBOX_MODE:
    raise ValueError("¡ERROR! No se puede usar modo sandbox en producción")

# configuracio Email
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # O tu servidor SMTP
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'manuel.24.sco@gmail.com'  # Reemplaza con tu email
EMAIL_HOST_PASSWORD = 'abrf mnpq snos rkuw'  # Reemplaza con tu contraseña
DEFAULT_FROM_EMAIL = 'manuel.24.sco@gmail.com'  # Debe ser el mismo que EMAIL_HOST_USER
SITE_NAME = 'DM Hotel'  # Para usar en el template


CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
CSRF_TRUSTED_ORIGINS = [
    'https://smpjwjtp-8000.brs.devtunnels.ms',
]